### ISSUE TITLE
ipv6.icanhazip service is down

### ISSUE THREAD

**Issue by LazaroOnline** [major/icanhaz#14]
Cannot get IP v6, the service is down at:
https://ipv6.icanhazip.com/

The browser displays this error:
ipv6.icanhazip.com’s server IP address could not be found.
Seems like the DNS for the "ipv6" subdomain was deleted, maybe by accident.

But the FAQ still references it as if it should be working:
https://major.io/icanhazip-com-faq/#how-do-i-control-whether-i-get-results-based-on-ipv4-or-ipv6

This service is important, it is used by the javascript library `public-ip` that has [over 80,000 downloads per week](https://www.npmjs.com/package/public-ip), and it's api to get the IPv6 is now broken due to this service being down.

Please, can you make it available again?
Thanks!

**Comment by stevehansen** [comment]
I think it's back online

**Comment by pruchay** [comment]
Looks like it's down again.
