### ISSUE TITLE
ipv4.icanhazip.com returning ipv6 addresses

### ISSUE THREAD

**Issue by glyph** [major/icanhaz#17]
I have a cron job that hits it every hour, and the first instance I received of this behavior was `Sun, 19 Apr 2020 01:59:59 -0000`.

Happy to provide more HTTP headers and stuff if that would be helpful.

**Comment by glyph** [comment]
Update: this only happens when accessed over HTTPS; plain-text HTTP seems to still work correctly.

And, update update: https://ipv4.icanhazip.com is now returning the TLS certificate for apex https://icanhazip.com, leading to validation failures.

**Comment by thompol** [comment]
Can you share exact cronjob?

**Comment by analotia** [comment]
I don't think this is possible because `ipv4.icanhazip.com` doesn't return any `AAAA` (ipv6) addresses.

`dig ipv4.icanhazip.com +short AAAA` is empty. 


Anyway, doing `curl -s4 icanhazip.com` is definitely a better choice.

**Comment by analotia** [comment]
Are you doing anything funky in `/etc/hosts` or in your DNS resolver?

**Comment by major** [comment]
Hey, there was some breakage a while back due to CloudFlare DNS limitations, unfortunately. It's been corrected for a while and the DNS records should be correct.

```
➜ host ipv4.icanhazip.com
ipv4.icanhazip.com has address 136.144.56.255
ipv4.icanhazip.com has address 147.75.47.199
➜ host ipv6.icanhazip.com
ipv6.icanhazip.com has IPv6 address 2604:1380:45f1:3c00::1
ipv6.icanhazip.com has IPv6 address 2604:1380:4111:9300::1
➜ host icanhazip.com
icanhazip.com has address 136.144.56.255
icanhazip.com has address 147.75.47.199
icanhazip.com has IPv6 address 2604:1380:4111:9300::1
icanhazip.com has IPv6 address 2604:1380:45f1:3c00::1

```

**Comment by cu** [comment]
Well that's weird. Around the time this bug was closed, https://ipv4.icanhazip.com started returning my IPv6 address instead of my ipv4 address. (Unless `curl -4` was used.)

Did some maintenance happen at that time?

**Comment by major** [comment]
@cu See https://github.com/major/icanhaz/issues/21#issuecomment-782267770 -- it's still being worked on.

**Comment by DavidWittman** [comment]
This is happening again

```
$ host ipv4.icanhazip.com
ipv4.icanhazip.com has address 104.18.7.156
ipv4.icanhazip.com has address 104.18.6.156
ipv4.icanhazip.com has IPv6 address 2606:4700::6812:79c
ipv4.icanhazip.com has IPv6 address 2606:4700::6812:69c
```

**Comment by major** [comment]
With the move to [Cloudflare running the site](https://major.io/2021/06/06/a-new-future-for-icanhazip/), they are working through the configuration. I let them know about this problem yesterday and they told me they are working through it.

**Comment by DavidWittman** [comment]
> With the move to [Cloudflare running the site](https://major.io/2021/06/06/a-new-future-for-icanhazip/), they are working through the configuration. I let them know about this problem yesterday and they told me they are working through it.

I figured that was the case... Sorry for bumping this issue, I wasn't sure where else to express the problem other than shouting out my window.

**Comment by major** [comment]
> I figured that was the case... Sorry for bumping this issue, I wasn't sure where else to express the problem other than shouting out my window.

No problem. 🤗

**Comment by thompol** [comment]
@major thank you for your hard work on this in the past years. I am very happy to see you are doing the best for yourself and I think Cloudflare is a very good maintainer for this project (please don't let this comment bite me in the ass @Cloudflare)

**Comment by major** [comment]
Thanks @thompol! 🤗

**Comment by WaelAlGhool** [comment]
I have the same problem, "ipv4.icanhazip.com" returns IPV6!!

**Comment by elisaado** [comment]
same

**Comment by andr0s** [comment]
Same, why is it closed?!

**Comment by thompol** [comment]
> With the move to [Cloudflare running the site](https://major.io/2021/06/06/a-new-future-for-icanhazip/), they are working through the configuration. I let them know about this problem yesterday and they told me they are working through it.

@andr0s

**Comment by zulh-civo** [comment]
Same here. I'm getting ipv6 when visiting http://ipv4.icanhazip.com.

**Comment by cc-asw** [comment]
I'm using http://ipv4.icanhazip.com with terraform to get my ip address. Yesterday it worked just fine and showed me the IPV4. Today the same script is showing the IPV6.

**Comment by elisaado** [comment]
It's showing my ipv4 address right now
