### ISSUE TITLE
Add sponsor or donation link

### ISSUE THREAD

**Issue by DavidWittman** [major/icanhaz#22]
Hey @major, would you consider adding a Github Sponsor page or other form of donation link to this project? I use icanhazip.com more than I care to admit, so I'd like to contribute some money for your time/hosting costs/etc.

**Comment by major** [comment]
That's very kind of you, @DavidWittman! At the moment, the only real expense I have are the domain names (under $100/year). I have help from:

* **Cloudflare**: Hosting icanhazip on workers for free
* **Equinix Metal / Packet.net**: Dedicated servers to help with the backend

However, one of my favorite causes to support is the [San Antonio Food Bank](https://safoodbank.org/donate/). If you love what I do, please send money there! There are still many people around San Antonio with no running water after the big ice/snow storm we just had. 💚

**Comment by DavidWittman** [comment]
Well thanks for all the time you've been putting into keeping icanhazip online lately. I'll ship some money to SAFB in honor of icanhazip.com.
