### ISSUE TITLE
ipv6.icanhazip.com returns ipv4 addresses

### ISSUE THREAD

**Issue by creeper123123321** [major/icanhaz#23]
to reproduce: ```curl https://ipv6.icanhazip.com -4```

**Comment by aam1r** [comment]
This started happening to me recently after I started using `1.1.1.1` as my DNS provider

**Comment by major** [comment]
With the move to [Cloudflare running the site](https://major.io/2021/06/06/a-new-future-for-icanhazip/), they are working through the configuration. I let them know about this problem yesterday and they told me they are working through it.
