### ISSUE TITLE
IPv6 retrieval does not work by any obvious method

### ISSUE THREAD

**Issue by Starwort** [major/icanhaz#25]
```
$ host icanhazip.com
icanhazip.com has address 172.67.9.138
icanhazip.com has address 104.22.19.188
icanhazip.com has address 104.22.18.188
icanhazip.com has IPv6 address 2606:4700:10::6816:12bc
icanhazip.com has IPv6 address 2606:4700:10::ac43:98a
icanhazip.com has IPv6 address 2606:4700:10::6816:13bc
$ curl ipv6.icanhazip.com
94.194.199.6
$ curl -6 icanhazip.com
curl: (7) Couldn't connect to server
```

**Comment by major** [comment]
@Starwort I've tried to reproduce this in a few places, but I cannot:

```
major@containers:~$ curl -6 icanhazip.com
2001:19f0:6401:xxxx:xxxx:xxxx:xxxx:xxxx
major@containers:~$ curl -6 ipv6.icanhazip.com
2001:19f0:6401:xxxx:xxxx:xxxx:xxxx:xxxx
```

There is a possibility that something on your system prefers IPv4 over IPv6 or the interface doesn't have an IPv6 configuration. If I go to a IPv4-only server, I do receive a v4 address back from icanhazip.com.

**Comment by Starwort** [comment]
This comes from my laptop, which has had this work previously (on Ubuntu 18.04, now Ubuntu 20.04) - is there any configuration you would need in order to debug this?

**Comment by major** [comment]
Hmm, if you run `curl -v`, does curl try to connect to the ipv6 address?

**Comment by Starwort** [comment]
```
$ curl -v -6 icanhazip.com
*   Trying 2606:4700:10::ac43:98a:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::ac43:98a: Network is unreachable
*   Trying 2606:4700:10::6816:13bc:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::6816:13bc: Network is unreachable
*   Trying 2606:4700:10::6816:12bc:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::6816:12bc: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
$ curl -v ipv6.icanhazip.com
*   Trying 172.67.164.120:80...
* TCP_NODELAY set
* Connected to ipv6.icanhazip.com (172.67.164.120) port 80 (#0)
> GET / HTTP/1.1
> Host: ipv6.icanhazip.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
94.194.199.6
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 22 Mar 2021 21:34:38 GMT
< Content-Type: text/plain
< Content-Length: 13
< Connection: keep-alive
< Set-Cookie: __cfduid=dda3bf775aa8f231269efee9f0fef29f21616448878; expires=Wed, 21-Apr-21 21:34:38 GMT; path=/; domain=.ipv6.icanhazip.com; HttpOnly; SameSite=Lax
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET
< X-OTTER: 🦦
< X-RTFM: Learn about this site at http://bit.ly/icanhazip-faq
< X-THANK-YOU: Many thanks to the fine people at Cloudflare for keeping this site afloat!
< cf-request-id: 08fd75917b0000fa8c21047000000001
< Report-To: {"max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=ty2e00MwhCNrGVz0IngxLy9aoRGJkaCtLyUenqP34suMCGDH2jSHy87Cd1TCJphnqoKe%2BSRXFfsMXOoe5zKCSgmrCDv8hUamZgTWVKi3eDAO7Rs%3D"}],"group":"cf-nel"}
< NEL: {"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 63428b959f36fa8c-AMS
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host ipv6.icanhazip.com left intact
```

**Comment by major** [comment]
Based on this output:

```
*   Trying 2606:4700:10::ac43:98a:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::ac43:98a: Network is unreachable
*   Trying 2606:4700:10::6816:13bc:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::6816:13bc: Network is unreachable
*   Trying 2606:4700:10::6816:12bc:80...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:10::6816:12bc: Network is unreachable
* Closing connection 0
```
something on your computer or your local network is preventing IPv6 packets from reaching icanhazip. This could be due to your local computer not having a v6 address assigned. Perhaps you could try `curl -6 ipv6.google.com` as well?

I can't reproduce this from multiple sources:

```
➜ curl -v ipv6.icanhazip.com
*   Trying 2606:4700:3030::6815:22c6:80...
* Connected to ipv6.icanhazip.com (2606:4700:3030::6815:22c6) port 80 (#0)
> GET / HTTP/1.1
> Host: ipv6.icanhazip.com
> User-Agent: curl/7.75.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
```

**Comment by Starwort** [comment]
> Perhaps you could try curl -6 ipv6.google.com as well?

That also fails - you're probably correct that that is the issue - does that mean that my laptop is sending IPv4 packets even when I specify `curl -6` - if not then you could give some more helpful feedback in the response?

**Comment by major** [comment]
Well, when this has happened to me at home, it usually means one of the following things is not working:

1) My workstation has IPv6 disabled for an interface.
2) My workstation didn't get an IPv6 router announcement from the nearby router/firewall and I don't have an IPv6 address provisioned.
3) I *do* have an IPv6 address on my workstation's network interface, but something is wrong on the router/firewall configuration that is blocking my IPv6 packets.
4) I *do* have an IPv6 address, but the IPv6 address block allocated to my router/firewall has changed and my workstation is using the old network block. (Happened a lot when Spectrum/Time Warner rolled out IPv6 support in my area.)

This can be challenging to troubleshoot but the first thing to look at is your network configuration on your workstation or laptop.

**Comment by Starwort** [comment]
Thanks for the info - maybe return that and a error message when ipv6 fails? I don't know how the code works or if that's possible, but it would be helpful if it happens to anyone else

**Comment by major** [comment]
@Starwort Well, the error you are seeing is coming from `curl` itself on your local workstation. The request isn't making it from your machine to my servers. 😞

**Comment by Starwort** [comment]
`curl ipv6.icanhazip.com` works but returns my IPv4 address - I meant in that case (I know you can't handle the case it doesn't leave my machine haha)

**Comment by major** [comment]
Yeah, that's one of the challenges I have right now. I've been under a DDoS for a while and Cloudflare is helping me with that, but there are some limitations with their DNS setup;

- icanhazip.com gets A + AAA records
- ipv4.icanhazip.com gets A records only
- ipv6.icanhazip.com gets A + AAAA records *(this is annoying)*

There's not a workaround for the ipv6.icanhazip.com A/AAAA record issue right now, but the fine folks at Cloudflare are keeping me updated on the effort to get that working. 🤞🏻

**Comment by Starwort** [comment]
I don't really know what this means, but good luck with it!
