### ISSUE TITLE
Cloudflare error using ddclient

### ISSUE THREAD

**Issue by Byter09** [major/icanhaz#26]
Hello,
I'm using `ddclient` and pointed it to `ipv4.icanhazip.com` and `ipv6.icanhazip.com` respectively.

For the last few days my ISP did not provide me an IPv6 address but I got it resolved. Now that everything is back online I noticed that my IPv6 address is not being updated anymore.

I turned on verbose mode in `ddclient` and was greeted with the HTML of a Cloudflare error page (I'm snipping unimportant bits and html where possible):
```
CONNECT:  ipv6.icanhazip.com
CONNECTED:  using HTTP
SENDING:  GET / HTTP/1.0
SENDING:   Host: ipv6.icanhazip.com
SENDING:   User-Agent: ddclient/3.9.1
SENDING:   Connection: close
SENDING:   
SENDING:   
RECEIVE:  HTTP/1.1 403 Forbidden
RECEIVE:  Date: Tue, 13 Apr 2021 23:33:42 GMT
RECEIVE:  Content-Type: text/html; charset=UTF-8
RECEIVE:  Connection: close
RECEIVE:  Set-Cookie: __cfduid=d6047941b71cd1d97696d094cc529d7071618356822; expires=Thu, 13-May-21 23:33:42 GMT; path=/; domain=.icanhazip.com; HttpOnly; SameSite=Lax
RECEIVE:  Cache-Control: max-age=15
RECEIVE:  Expires: Tue, 13 Apr 2021 23:33:57 GMT
RECEIVE:  X-Frame-Options: SAMEORIGIN
RECEIVE:  cf-request-id: 096f2e7b2200001f2945b95000000001
RECEIVE:  Server: cloudflare
RECEIVE:  CF-RAY: 63f8803e9d281f29-FRA

RECEIVE:      Please enable cookies.
RECEIVE:          Sorry, you have been blocked
RECEIVE:          You are unable to access icanhazip.com

RECEIVE:              Why have I been blocked?
RECEIVE:              This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

RECEIVE:              What can I do to resolve this?
RECEIVE:              You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
RECEIVE:      Cloudflare Ray ID: 63f8803e9d281f29
RECEIVE:      Your IP: XXX
WARNING:  found neither ipv4 nor ipv6 address
WARNING:  unable to determine IP address
```

Quite unsure why this is all of a sudden. I'm pretty sure a timeout of 5 minutes between checks is fairly okay and should not be regarded as spam.

Is this something I have to fix on my end? Is maybe my `ddclient.conf` faulty? All I told it was to go to `ipv6.icanhazip.com` and to update my DNS entry using the cloudflare protocol using the result of that HTTP result.

Funnily enough I could tell it to parse the error to get the IP it's listing, hah.

Also, quite odd: When I execute `curl -6 ipv6.icanhazip.com` inside of the docker container running ddclient manually, I get a correct result back, so I'm unsure if this a problem with ddclient, the docker container or `icanhazip.com` and its usage of Cloudflare.

**Comment by Byter09** [comment]
I have resolved my issue by simply switching `ddclient`s config from `use=web, web=ipvX.icanhazip.com` to `use=cmd, cmd='curl -X ipvX.icanhazip.com` using X for the IP version.

**Comment by major** [comment]
@Byter09 Glad you found a workaround! The amount of traffic that icanhazip usually received *per month* started happening *per day* and I've been using Cloudflare to help me weed out some offenders who are abusing the site.
