### ISSUE TITLE
Traffic stats?

### ISSUE THREAD

**Issue by LordMike** [major/icanhaz#30]
I just read this article: https://major.io/2021/06/06/a-new-future-for-icanhazip/

Are the numbers for real?  -- just for icanhazip.com or also for the other sites you have?

This is insane. :|

**Comment by major** [comment]
@LordMike It's true! Even after a bunch of filtering and DDoS mitigation, there are still 11-12B requests per day on the site. 🥵

**Comment by LordMike** [comment]
God damn. Were the stats just for the IP site, or also for the sibling sites?

Also - I imagine you could cache the more complex items using Cloudflare KV storage system, such as trace routes or reverse lookups.

**Comment by major** [comment]
So icanhazip is the biggest by far. The other ones are easily manageable.

**Comment by LordMike** [comment]
And all that for an `echo $client_ip` service :D

Thanks for the answers, have a greay day.

**Comment by major** [comment]
@LordMike No problem! Have a good one. 🎉
