### ISSUE TITLE
icanhazepoch reports time in milliseconds

### ISSUE THREAD

**Issue by nosoop** [major/icanhaz#32]
Hi! Thanks for originally providing these services.

```
$ curl https://icanhazepoch.com
1624878309939
$ python3 -c "import time; print(int(time.time()))"
1624878335
```

I think this change happened at some point between September of last year and February of this year; used it occasionally for naming manually-created archives (Windows machine 😅).

**Comment by major** [comment]
@nosoop Good catch! I switched over to Cloudflare workers for the site a while back and apparently my Javascript time knowledge isn't that great. It should be fixed now.

```
➜ curl icanhazepoch.com
1625055536
```

**Comment by nosoop** [comment]
Yep, it's correct now.  Thanks!
