### ISSUE TITLE
blocked by Sky Broadband

### ISSUE THREAD

**Issue by aaronmehar** [major/icanhaz#5]
Major, for some reason, as I discovered icanhazip.com is blocked by Sky Broadcasting, an ISP in the UK

**Comment by major** [comment]
Thanks for the tip, @aaronmehar. Is there any information displayed in the browser about contacting Sky about it?

**Comment by isaac-friedman** [comment]
I forgot that I was on this project's mailing list but I just poked around
and Sky has a dedicated email address for
"websites miscategorised (sic, b/c Queen's English) by Sky Broadband
Shield" which sounds closest to this issue.
crsupport@sky.uk
https://contactus.sky.com/uk/sky-broadband/report-miscategorised-website

**Comment by aaronmehar** [comment]
@major ill have to check.. was on the phone with a customer :( sad time to discovered this.. I know some people with Sky, so ill check.

**Comment by major** [comment]
Just emailed them at their link.
