### ISSUE TITLE
Common Name of SSL certificate of ipv6.icanhazip.com is invalid

### ISSUE THREAD

**Issue by andreaskoch** [major/icanhaz#6]
The SSL certificate for the [https://ipv6.icanhazip.com](https://ipv6.icanhazip.com) subdomain is not valid:

![Screenshot of https://ipv6.icanhazip.com with Chrome SSL warning](https://cloud.githubusercontent.com/assets/247364/14059816/6b59101a-f34f-11e5-9f1c-b2a459cf7b2d.png)

I know, I can just use [https://icanhazip.com](https://icanhazip.com) instead. But I just wanted to point that out - especially since the certificate of [ipv4.icanhazip.com](https://ipv4.icanhazip.com) is valid.

**Comment by major** [comment]
Hey @andreaskoch, thanks for the bug. I have not had the change to get a SSL certificate for the ipv6 domain yet.  I'd like to get LetsEncrypt working for that, but I need some more Ansible automation work done first.

**Comment by major** [comment]
This should be fixed now, @andreaskoch. Let me know if you're still having issues! :)
